const images = {
    avata: require('./image/avata.png'),
    background: require('./image/background.png'),
    banner: require('./image/banner.png'),
    banner1: require('./image/banner1.jpeg'),
    banner3: require('./image/banner3.jpeg'),
    banner_restaurant: require('./image/banner_restautant.png'),

    icon_back: require('./image/icon_back.png'),
    logoFB: require('./image/facebook.png'),
    flag_vn: require('./image/flag_vn.png'),
    icon_delete_textinput: require('./image/delete_text_input.png'),
    recover_password: require('./image/modal_forgot_password.png'),
    icon_search: require('./image/icon_search.png'),
    icon_filter: require('./image/icon_filter.png'),
    icon_star: require('./image/icon_star.png'),
    icon_explore: require('./image/icons_tabbar_Explore.png'),
    icon_show_all: require('./image/icon_show_all.png'),
    icon_notice: require('./image/icon_notice.png'),
    icon_pay: require('./image/icon_pay.png'),
    icon_reward: require('./image/icon_reward.png'),
    icon_promo_code: require('./image/icon_promp_code.png'),
    icon_setting: require('./image/icon_setting.png'),
    icon_invite: require('./image/icon_invite.png'),
    icon_help: require('./image/icon_help.png'),
    icon_about: require('./image/icon_about.png'),
    icon_more: require('./image/icon_more.png'),
    icon_camera: require('./image/icon_camera.png'),
    vip_member: require('./image/vip_member.png'),
    icon_location: require('./image/location.png'),
    icon_white_arrow: require('./image/icon_white_arrow.png'),
    icon_bookmark: require('./image/icon_bookmark.png'),
    icon_bgbookmark: require('./image/icon_bg_bookmark.png'),
    icon_cart: require('./image/icon_cart.png'),
    icon_close: require('./image/icon_close.png'),
    icon_home2: require('./image/icon_home2.png'),
    icon_myooder2: require('./image/icon_myoder2.png'),
    icon_favourite2: require('./image/icon_favourite3.png'),
    icon_user2: require('./image/icon_user2.png'),
    icon_home1: require('./image/icon_home1.png'),
    icon_myoder1: require('./image/icon_oder1.png'),
    icon_favourite1: require('./image/icon_favourite1.png'),
    ion_user1: require('./image/icon_user1.png'),
    icon_star00: require('./image/icon_star00.png'),
    icon_mark00: require('./image/icon_mark00.png'),
    icon_image00: require('./image/icon_image00.png'),
    icon_star01: require('./image/icon_star01.png'),
    icon_mark01: require('./image/icon_mark01.png'),
    icon_image01: require('./image/icon_image01.png'),
    icon_share_white: require('./image/icon_share_white.png'),
    icon_mark_white01: require('./image/icon_mark_white01.png'),
    icon_more_detail: require('./image/icon_more_detail.png'),
    icon_down: require('./image/icon_down.png'),
    icon_add: require('./image/icon_add.png'),
    icon_check: require('./image/icon_check.png'),
    icon_bestsell: require('./image/icon_bestsell.png'),
    icon_check01: require('./image/icons-check01.png'),
    vantay: require('./image/vantay.png'),
    icon_paya: require('./image/icon_paya.png'),
    icon_visa: require('./image/icon_visa.png'),
    icon_mastercard: require('./image/icon_mastercard.png'),
    icon_check_pay: require('./image/icon_check_pay.png'),

    food1: require('./image/food1.png'),
    food2: require('./image/food2.png'),
    food3: require('./image/food3.png'),
    food4: require('./image/food4.png'),
    food5: require('./image/food5.png'),
    food6: require('./image/food6.png'),
    food7: require('./image/food7.png'),
    food8: require('./image/food9.png'),
    food9: require('./image/food10.png'),
    asia_food: require('./image/asia_food.png'),
    desserts_food: require('./image/deser_food.png'),
    fast_food: require('./image/fast_food.png'),
    vietnames_food: require('./image/vietnamese_food.png'),
    shushi_food: require('./image/sushi_food.png'),
    sandwhiches_food: require('./image/sandwich_food.png'),
    new_travonburgh_food: require('./image/newtravon_food.png'),
    candiceborough_food: require('./image/candi_food.png'),
    pt0: require('./image/pt0.png'),
    pt1: require('./image/pt1.png'),
    pt2: require('./image/pt2.png'),
    pt3: require('./image/pt3.png'),




};

export default images;
